export const breadcrumbs = {
    '/': 'Home',
    '/info': 'Home > Recursos',
    '/quiz': 'Home > Quiz',
    '/profile': 'Home > Perfil',
    '/setupquiz': 'Home > Configura Partida',
    '/results' : 'Home > Resultados',
    '/login': 'Home > Perfil > Inicia sesión',
    '/register': 'Home > Perfil > Registrarse',
    '/myprofile': 'Home > Mi Perfil',
    '/changepassword': 'Home > Mi Perfil > Cambia contraseña',
    '/mythings': 'Home > Mi Perfil > Mis cosas',
    '/routines': 'Home > Rutinas',
    '/createroutine': 'Home > Rutinas > Crea rutina',
    '/searchroutines': 'Home > Rutinas > Busca rutinas',
    '/myroutines': '... > Mis cosas > Mis rutinas',
    '/techniques': 'Home > Técnicas',
    '/createtechnique': 'Home > Técnicas > Crea técnica',
    '/searchtechniques': 'Home > Técnicas > Busca técnicas',
    '/mytechniques': '... > Mis cosas > Mis técnicas',
    '/setupflashcards': 'Home > Recursos > Flashcards',
    '/flashcards': '... > Recursos > Flashcards > Flashcard',
    '/creatediary': '... > Mis diarios > Crear diario',
    '/mydiaries': '... > Mis diarios > Diarios creados',
    '/diaries': '... > Mis cosas > Mis diarios',
    '/events': 'Home > Eventos',
    '/createevent': 'Home > Eventos > Crear evento',
    '/searchevents': 'Home > Eventos > Buscar eventos',
    '/myevents': '... > Mis cosas > Mis eventos',
    '/calendar': 'Home > Recursos > Calendario',
}